ELDER_GUARDIAN: 20
WITHER_SKELETON: 20
STRAY: 20
WITHER_SKULL: 20
HUSK: 20
ZOMBIE_VILLAGER: 20
SKELETON_HORSE: 20
ZOMBIE_HORSE: 20
DONKEY: 20
MULE: 20
EVOKER: 20
VEX: 20
VINDICATOR: 20
ILLUSIONER: 20
CREEPER: 20
SKELETON: 20
SPIDER: 20
GIANT: 20
ZOMBIE: 20
SLIME: 20
GHAST: 20
ZOMBIFIED_PIGLIN: 20
ENDERMAN: 20
CAVE_SPIDER: 20
SILVERFISH: 20
BLAZE: 20
MAGMA_CUBE: 20
ENDER_DRAGON: 20
WITHER: 20
BAT: 20
WITCH: 20
ENDERMITE: 20
GUARDIAN: 20
SHULKER: 20
PIG: 20
SHEEP: 20
COW: 20
CHICKEN: 20
SQUID: 20
WOLF: 20
MUSHROOM_COW: 20
SNOWMAN: 20
OCELOT: 20
IRON_GOLEM: 20
HORSE: 20
RABBIT: 20
POLAR_BEAR: 20
LLAMA: 20
PARROT: 20
VILLAGER: 20
TURTLE: 20
PHANTOM: 20
COD: 20
SALMON: 20
PUFFERFISH: 20
TROPICAL_FISH: 20
DROWNED: 20
DOLPHIN: 20
CAT: 20
PANDA: 20
PILLAGER: 20
RAVAGER: 20
TRADER_LLAMA: 20
WANDERING_TRADER: 20
FOX: 20
BEE: 20
HOGLIN: 20
PIGLIN: 20
STRIDER: 20
ZOGLIN: 20
PIGLIN_BRUTE: 20
PLAYER: 20